version: 2.1
orbs:
  node: circleci/node@3.0.0
  
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: backoffice/taller2airbnb      

    docker:
      - image: circleci/node:12
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          
          command: |
            docker build -t $IMAGE_NAME:latest .
workflows:
  node-tests:
    jobs:
      - node/test
      - build
